FROM rasa/rasa-sdk:latest

USER root
RUN apt-get update
RUN apt update 
#RUN apt-get install -y python-pip python-dev default-libmysqlclient-dev

RUN pip install requests
RUN pip install mysql-connector-python
#RUN pip install mysql

USER 1001 
